fix nix build
input-output-hk/cardano-addresses pull request #103
Opened 2021-02-02 19:53 UTC by disassembler

2021-02-04 09:07 UTC, hamishmack commented
I included these changes and made some more nix fixes in #104

2021-02-15 06:16 UTC, rvl requested changes
Thanks @disassembler

2021-02-15 06:16 UTC, rvl commented on cabal.project.freeze
> -constraints: any.ALUT ==2.4.0.3,
We need a cabal.project.freeze file - is it possible to regenerate this?

2021-02-23 02:03 UTC, rvl approved these changes

2021-03-02 10:19 UTC, rvl commented
I have rebased and squashed - thanks for the fixes @hamishmack @disassembler.
Unfortunately I had to give up on `cabal.project.freeze` - but `index-state` should achieve the same thing more or less.

2021-03-02 10:19 UTC, merged